<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <LangVersion>default</LangVersion>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\App.Contracts.BLL\App.Contracts.BLL.csproj" />
      <ProjectReference Include="..\App.Contracts.DAL\App.Contracts.DAL.csproj" />
      <ProjectReference Include="..\App.DAL.EF\App.DAL.EF.csproj" />
      
      <ProjectReference Include="..\Base.BLL\Base.BLL.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="AutoMapper" Version="16.1.1" />
      <PackageReference Include="Microsoft.Build" Version="18.4.0" />
      <PackageReference Include="Microsoft.Extensions.Http" Version="10.0.5" />
      <PackageReference Include="Microsoft.IdentityModel.Tokens" Version="8.17.0" />
      <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
      <PackageReference Include="RESTCountries.NET" Version="3.6.0" />
      <PackageReference Include="SixLabors.ImageSharp" Version="3.1.12" />
    </ItemGroup>

</Project>
