<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <LangVersion>default</LangVersion>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\App.Contracts.BLL\App.Contracts.BLL.csproj" />
      <ProjectReference Include="..\App.Contracts.DAL\App.Contracts.DAL.csproj" />
      <ProjectReference Include="..\App.DAL.EF\App.DAL.EF.csproj" />
      
      <ProjectReference Include="..\Base.BLL\Base.BLL.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="AutoMapper" Version="15.1.0" />
      <PackageReference Include="Microsoft.Build" Version="17.14.28" />
      <PackageReference Include="RESTCountries.NET" Version="3.5.0" />
      <PackageReference Include="SixLabors.ImageSharp" Version="3.1.11" />
      <PackageReference Include="System.Text.Encodings.Web" Version="9.0.10" />
    </ItemGroup>

</Project>
