# This is a generated file. Not intended for manual editing.
version: "3.9"
services:
  app:
    entrypoint:
    - "/riderDebugger/linux-x64/dotnet/dotnet"
    - "/riderDebugger/JetBrains.Debugger.Worker.exe"
    - "--mode=server"
    - "--frontend-port=57100"
    - "--backend-port=57300"
    environment:
      RIDER_DEBUGGER_LOG_DIR: "/riderLogs"
      RESHARPER_LOG_CONF: "/riderLogsConf/backend-log.xml"
    ports:
    - "61152:57100"
    - "61153:57300"
    volumes:
    - "C:\\Users\\meril\\AppData\\Local\\JetBrains\\RiderRemoteDebugger\\2023.1.2\\\
      Linux64:/riderDebugger"
    - "C:\\Program Files\\JetBrains\\JetBrains Rider 2023.1.1/bin:/riderLogsConf"
    - "C:\\Users\\meril\\AppData\\Local\\JetBrains\\Rider2023.1\\log\\DebuggerWorker\\\
      JetBrains.Debugger.Worker.2023_6_06_18_41_05:/riderLogs:rw"
