//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Resources.Areas.App.Domain.AdminArea {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Drive {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Drive() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("App.Resources.Areas.App.Domain.AdminArea.Drive", typeof(Drive).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept.
        /// </summary>
        public static string Accept {
            get {
                return ResourceManager.GetString("Accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accepted.
        /// </summary>
        public static string Accepted {
            get {
                return ResourceManager.GetString("Accepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drive Acceptance Date and Time.
        /// </summary>
        public static string AcceptedDateAndTime {
            get {
                return ResourceManager.GetString("AcceptedDateAndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accepting Drive.
        /// </summary>
        public static string AcceptingDrive {
            get {
                return ResourceManager.GetString("AcceptingDrive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Awaiting for Confirmation.
        /// </summary>
        public static string AwaitingForConfirmation {
            get {
                return ResourceManager.GetString("AwaitingForConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        public static string CommentText {
            get {
                return ResourceManager.GetString("CommentText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer.
        /// </summary>
        public static string Customer {
            get {
                return ResourceManager.GetString("Customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decline.
        /// </summary>
        public static string Decline {
            get {
                return ResourceManager.GetString("Decline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Declined.
        /// </summary>
        public static string Declined {
            get {
                return ResourceManager.GetString("Declined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drive Decline Date and Time.
        /// </summary>
        public static string DeclineDateAndTime {
            get {
                return ResourceManager.GetString("DeclineDateAndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Declining Drive.
        /// </summary>
        public static string DecliningDrive {
            get {
                return ResourceManager.GetString("DecliningDrive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination Address.
        /// </summary>
        public static string DestinationAddress {
            get {
                return ResourceManager.GetString("DestinationAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination Floor Number.
        /// </summary>
        public static string DestinationFloorNumber {
            get {
                return ResourceManager.GetString("DestinationFloorNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drive.
        /// </summary>
        public static string DriveName {
            get {
                return ResourceManager.GetString("DriveName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drives.
        /// </summary>
        public static string Drives {
            get {
                return ResourceManager.GetString("Drives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished.
        /// </summary>
        public static string Finished {
            get {
                return ResourceManager.GetString("Finished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drive End Date and Time.
        /// </summary>
        public static string FinishedDateAndTime {
            get {
                return ResourceManager.GetString("FinishedDateAndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has an Assistant?.
        /// </summary>
        public static string HasAnAssistant {
            get {
                return ResourceManager.GetString("HasAnAssistant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Does the Destination Building Have an Elevator?.
        /// </summary>
        public static string HasAnElevatorInTheDestinationBuilding {
            get {
                return ResourceManager.GetString("HasAnElevatorInTheDestinationBuilding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Does the Pickup Building Have an Elevator?.
        /// </summary>
        public static string HasAnElevatorInThePickupBuilding {
            get {
                return ResourceManager.GetString("HasAnElevatorInThePickupBuilding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In-Progress.
        /// </summary>
        public static string InProgress {
            get {
                return ResourceManager.GetString("InProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date and Time of the Drive.
        /// </summary>
        public static string InProgressDateAndTime {
            get {
                return ResourceManager.GetString("InProgressDateAndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driver.
        /// </summary>
        public static string JobTitle {
            get {
                return ResourceManager.GetString("JobTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do You Need Assistance Entering the Building?.
        /// </summary>
        public static string NeedAssistanceEnteringTheBuilding {
            get {
                return ResourceManager.GetString("NeedAssistanceEnteringTheBuilding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do You Need Assistance Leaving the Building?.
        /// </summary>
        public static string NeedAssistanceLeavingTheBuilding {
            get {
                return ResourceManager.GetString("NeedAssistanceLeavingTheBuilding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Passengers.
        /// </summary>
        public static string NumberOfPassengers {
            get {
                return ResourceManager.GetString("NumberOfPassengers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pickup Address.
        /// </summary>
        public static string PickupAddress {
            get {
                return ResourceManager.GetString("PickupAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick Up Date and Time.
        /// </summary>
        public static string PickUpDateAndTime {
            get {
                return ResourceManager.GetString("PickUpDateAndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick Up Floor Number.
        /// </summary>
        public static string PickupFloorNumber {
            get {
                return ResourceManager.GetString("PickupFloorNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule.
        /// </summary>
        public static string Schedule {
            get {
                return ResourceManager.GetString("Schedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End the Drive.
        /// </summary>
        public static string SettingDriveIntoFinishedState {
            get {
                return ResourceManager.GetString("SettingDriveIntoFinishedState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start the Drive.
        /// </summary>
        public static string SettingDriveIntoInProgressState {
            get {
                return ResourceManager.GetString("SettingDriveIntoInProgressState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shift Duration.
        /// </summary>
        public static string ShiftDurationTime {
            get {
                return ResourceManager.GetString("ShiftDurationTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status of Booking.
        /// </summary>
        public static string StatusOfBooking {
            get {
                return ResourceManager.GetString("StatusOfBooking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status of Drive.
        /// </summary>
        public static string StatusOfDrive {
            get {
                return ResourceManager.GetString("StatusOfDrive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle.
        /// </summary>
        public static string VehicleIdentifier {
            get {
                return ResourceManager.GetString("VehicleIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle Type.
        /// </summary>
        public static string VehicleType {
            get {
                return ResourceManager.GetString("VehicleType", resourceCulture);
            }
        }
    }
}
