//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Resources.Areas.App.Domain.AdminArea {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Photo {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Photo() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("App.Resources.Areas.App.Domain.AdminArea.Photo", typeof(Photo).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin.
        /// </summary>
        public static string Admin {
            get {
                return ResourceManager.GetString("Admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to Gallery.
        /// </summary>
        public static string BackToGallery {
            get {
                return ResourceManager.GetString("BackToGallery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer.
        /// </summary>
        public static string Customer {
            get {
                return ResourceManager.GetString("Customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory Title Id.
        /// </summary>
        public static string DirectoryTitleId {
            get {
                return ResourceManager.GetString("DirectoryTitleId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driver.
        /// </summary>
        public static string Driver {
            get {
                return ResourceManager.GetString("Driver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Name.
        /// </summary>
        public static string FileName {
            get {
                return ResourceManager.GetString("FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Name in the Directory.
        /// </summary>
        public static string FileNameInDirectory {
            get {
                return ResourceManager.GetString("FileNameInDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo Full Path.
        /// </summary>
        public static string PhotoFullPath {
            get {
                return ResourceManager.GetString("PhotoFullPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo.
        /// </summary>
        public static string PhotoName {
            get {
                return ResourceManager.GetString("PhotoName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photos.
        /// </summary>
        public static string Photos {
            get {
                return ResourceManager.GetString("Photos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo URL.
        /// </summary>
        public static string PhotoURL {
            get {
                return ResourceManager.GetString("PhotoURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thumbnail Directory Id.
        /// </summary>
        public static string ThumbnailDirectoryId {
            get {
                return ResourceManager.GetString("ThumbnailDirectoryId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thumbnail Full Path.
        /// </summary>
        public static string ThumbnailFullPath {
            get {
                return ResourceManager.GetString("ThumbnailFullPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thumbnail Relative Path.
        /// </summary>
        public static string ThumbnailRelativePath {
            get {
                return ResourceManager.GetString("ThumbnailRelativePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title .
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload a back-side photo of the vehicle..
        /// </summary>
        public static string UploadAPhotoOfTheVehiclesBackside {
            get {
                return ResourceManager.GetString("UploadAPhotoOfTheVehiclesBackside", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload a front-side photo of the vehicle. The plate number must be clearly distinguished..
        /// </summary>
        public static string UploadAPhotoOfTheVehiclesFrontSide {
            get {
                return ResourceManager.GetString("UploadAPhotoOfTheVehiclesFrontSide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload a photo of the vehicle&apos;s interior..
        /// </summary>
        public static string UploadAPhotoOfTheVehiclesInterior {
            get {
                return ResourceManager.GetString("UploadAPhotoOfTheVehiclesInterior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload a side photo of the vehicle.
        /// </summary>
        public static string UploadAPhotoOfTheVehiclesSide {
            get {
                return ResourceManager.GetString("UploadAPhotoOfTheVehiclesSide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle.
        /// </summary>
        public static string Vehicle {
            get {
                return ResourceManager.GetString("Vehicle", resourceCulture);
            }
        }
    }
}
